### ISSUE TITLE
Tapestry textures need work

### ISSUE THREAD

**Issue by Napiophelios** [minetest-mods/castle#16]
the current material for tapestries looks awkward in the game
![tapestry_000](https://cloud.githubusercontent.com/assets/8119411/15099326/42301e84-1520-11e6-96e8-bb9f975870d7.png)

we can either turn the textures so they look more natural:
![tapestry_001](https://cloud.githubusercontent.com/assets/8119411/15099330/588ec748-1520-11e6-841d-3311b47c85a1.png)

or include a custom overlay for the tapestry material:
![tapestry_002](https://cloud.githubusercontent.com/assets/8119411/15099332/6c187cd2-1520-11e6-82e5-429da98d734f.png)

I prefer the overlay idea my self, but the colors arent as vibrant, so I doubt other players will.

**Comment by Philipbenr** [comment]
Mmmm... you're right...

I think there is an easy way to rotate the textures, but that won't work for all textures. I'll look into this...
