### ISSUE TITLE
Changing Licenses

### ISSUE THREAD

**Issue by Philipbenr** [minetest-mods/castle#23]
@Napiophelios @sofar @VanessaE @Wayward1 

I want to change the mod's license to MIT (from GPLv3). I was planning this for a while, and this is the only mod that I haven't changed I think. I will write up a contributors list in the modpack.txt, along with more credit in the individual licenses. Does anybody have an issue with this? Just asking as to be sure nobody gets POed and leaves like the Minetest engine team.  XD

**Comment by VanessaE** [comment]
:+1:

I have no objections.

**Comment by sofar** [comment]
:+1: Please, go ahead.

**Comment by Napiophelios** [comment]
:+1:  I have no objections either.

**Comment by Philipbenr** [comment]
Well, then I think that I'll go ahead and do it. Thanks for the confirmation, and all of your contributions. You have no idea how much it really helped.  ;)

**Comment by Wayward1** [comment]
Kinda late, but sounds good to me too

**Comment by Philipbenr** [comment]
And thank you to you too Wayward1. Every contribution helps, and as I said, you have no idea how much it helps. And thanks to @sofar for all his work in the minetest-mods repo. You guys are awesome.

Edit: See commit descriptions for more details on the licensing if you would like. Its not as simple as I would like ;)
