### ISSUE TITLE
A tagged release with downloadable bundle is needed

### ISSUE THREAD

**Issue by FaceDeer** [minetest-mods/castle#35]
Now that this has been converted into a modpack using submodules a release with a corresponding downloadable zip needs to be tagged (since GitHub's built-in download only has empty folders for the submodules). Similar to [how I did it on my fork](https://github.com/FaceDeer/castle/releases). The zip from over there could be used directly, it's currently up-to-date.

**Comment by SnarkBoojum** [comment]
I may also add that properly tagging releases would allow me to work on packaging it for Debian.

**Comment by Niklp09** [comment]
Obsolete due to https://github.com/minetest-mods/castle/commit/a35e564b81739c02bc5e418b5a14940bd9739638.
