### ISSUE TITLE
Use the Submodules Alternative tool

### ISSUE THREAD

**Issue by Panquesito7** [minetest-mods/castle#41]
### Description

With the [Submodules Alternative](https://github.com/Panquesito7/submodules-alternative) tool, anyone can easily clone the submodules without having to install Git or run any extra commands.
[PanqKart](https://github.com/panqkart/panqkart) already uses [Submodules Alternative](https://github.com/Panquesito7/submodules-alternative) and it has been working very well. The tool is still WIP and might have a few bugs, but with the proper configuration, it should work completely fine.

Let me know your thoughts. Thanks! 🙂

**Comment by Niklp09** [comment]
Obsolete due to https://github.com/minetest-mods/castle/commit/a35e564b81739c02bc5e418b5a14940bd9739638.
